name: local
variables:
  - name: base_url
    value: http://localhost:3000
  - name: userId
    value: 8FIiM4zzB2fkWxBgAsRrYkXsiXzpXXnF
  - name: taskId
    value: ""
  - name: token
    value: lStSAnqIkjH8Mb1jTGx7F0Dzeu78LlLJ
